# Print dates on 4 different runners
name: complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  windows:
    runs-on: windows-latest
    steps:
      - run: date
  mac:
    runs-on: macos-latest
    steps:
      - run: date
  depends:
    needs : [ubuntu, windows, mac]
    runs-on: macos-latest 
    steps:
      - run: date
