# Define the GitHub Actions workflow for running tests on push events
name: My First GitHub Actions

# Trigger the workflow on push events
on:
  push:
    branches:
      - main

# Define jobs for the workflow
jobs:
  # Define the 'build' job for running tests
  build:
    runs-on: ubuntu-latest

    # Define a strategy for running tests with different Python versions
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python with the specified version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run tests
      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py --verbose
